Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from skopt.optimizer import Optimizer

optimizer = Optimizer(5, base_estimator,
                          n_initial_points=5,
                          initial_point_generator="sobol",
                          n_jobs=n_jobs,
                          acq_func=acq_func, acq_optimizer=acq_optimizer,
                          random_state=random_state,
                          model_queue_size=model_queue_size,
                          acq_optimizer_kwargs=acq_optimizer_kwargs,
                          acq_func_kwargs=acq_func_kwargs)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [10], line 3[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mskopt[39;00m[38;5;21;01m.[39;00m[38;5;21;01moptimizer[39;00m [38;5;28;01mimport[39;00m Optimizer
[0;32m----> 3[0m optimizer [38;5;241m=[39m Optimizer([38;5;241m5[39m, base_estimator,
[1;32m      4[0m                           n_initial_points[38;5;241m=[39m[38;5;241m5[39m,
[1;32m      5[0m                           initial_point_generator[38;5;241m=[39m[38;5;124m"[39m[38;5;124msobol[39m[38;5;124m"[39m,
[1;32m      6[0m                           n_jobs[38;5;241m=[39mn_jobs,
[1;32m      7[0m                           acq_func[38;5;241m=[39macq_func, acq_optimizer[38;5;241m=[39macq_optimizer,
[1;32m      8[0m                           random_state[38;5;241m=[39mrandom_state,
[1;32m      9[0m                           model_queue_size[38;5;241m=[39mmodel_queue_size,
[1;32m     10[0m                           acq_optimizer_kwargs[38;5;241m=[39macq_optimizer_kwargs,
[1;32m     11[0m                           acq_func_kwargs[38;5;241m=[39macq_func_kwargs)

[0;31mNameError[0m: name 'base_estimator' is not defined
NameError: name 'base_estimator' is not defined

