Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor

# Build a random forest regressor and fit it to the training data
regr = RandomForestRegressor(max_depth=20, random_state=0)
regr.fit(X_train, y_train)

# Plot predictions for val as a kdeplot
sns.kdeplot(
    y_val,
    regr.predict(X_val),
    fill=True,
)

# Add a parity line and x/y axis labels
plt.plot([np.min(y_val), np.max(y_val)], [np.min(y_val), np.max(y_val)], "k--")
plt.axis("square")
plt.xlabel("Actual DFT Energy [eV]")
plt.ylabel("Predicted DFT Energy [eV]")
plt.show()

from sklearn.metrics import mean_absolute_error
print(f'The mean absolute error is {mean_absolute_error(y_val, regr.predict(X_val)):.2f} eV')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn [5], line 11[0m
[1;32m      8[0m regr[38;5;241m.[39mfit(X_train, y_train)
[1;32m     10[0m [38;5;66;03m# Plot predictions for val as a kdeplot[39;00m
[0;32m---> 11[0m sns[38;5;241m.[39mkdeplot(
[1;32m     12[0m     y_val,
[1;32m     13[0m     regr[38;5;241m.[39mpredict(X_val),
[1;32m     14[0m     fill[38;5;241m=[39m[38;5;28;01mTrue[39;00m,
[1;32m     15[0m )
[1;32m     17[0m [38;5;66;03m# Add a parity line and x/y axis labels[39;00m
[1;32m     18[0m plt[38;5;241m.[39mplot([np[38;5;241m.[39mmin(y_val), np[38;5;241m.[39mmax(y_val)], [np[38;5;241m.[39mmin(y_val), np[38;5;241m.[39mmax(y_val)], [38;5;124m"[39m[38;5;124mk--[39m[38;5;124m"[39m)

[0;31mTypeError[0m: kdeplot() takes from 0 to 1 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given
TypeError: kdeplot() takes from 0 to 1 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given

