Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
from lmfit.models import PolynomialModel, SineModel

poly_model = PolynomialModel(degree=4, independent_vars=["x"])
sine_model = SineModel(independent_vars=["x"])
model = sine_model + poly_model
params = model.make_params(
    c0=1, c1=1, c2=1, c3=1, c4=1, frequency=2 * np.pi, amplitude=10, shift=-2 * np.pi
)
result = model.fit(y_train, params, x=X_train[:, 0])
y_val_pred = polysin_result.eval(x=X_val[:, 0])

mae = mean_absolute_error(y_val, y_val_pred)
rmse = mean_squared_error(y_val, y_val_pred) ** 0.5
print(f"The MAE for the polynomial+sin model fit is {mae:0.2f} C")
print(f"The RMSE for the  polynomial+sin model fit is {rmse:0.2f} C")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [19][0m, in [0;36m<cell line: 11>[0;34m()[0m
[1;32m      7[0m params [38;5;241m=[39m model[38;5;241m.[39mmake_params(
[1;32m      8[0m     c0[38;5;241m=[39m[38;5;241m1[39m, c1[38;5;241m=[39m[38;5;241m1[39m, c2[38;5;241m=[39m[38;5;241m1[39m, c3[38;5;241m=[39m[38;5;241m1[39m, c4[38;5;241m=[39m[38;5;241m1[39m, frequency[38;5;241m=[39m[38;5;241m2[39m [38;5;241m*[39m np[38;5;241m.[39mpi, amplitude[38;5;241m=[39m[38;5;241m10[39m, shift[38;5;241m=[39m[38;5;241m-[39m[38;5;241m2[39m [38;5;241m*[39m np[38;5;241m.[39mpi
[1;32m      9[0m )
[1;32m     10[0m result [38;5;241m=[39m model[38;5;241m.[39mfit(y_train, params, x[38;5;241m=[39mX_train[:, [38;5;241m0[39m])
[0;32m---> 11[0m y_val_pred [38;5;241m=[39m [43mpolysin_result[49m[38;5;241m.[39meval(x[38;5;241m=[39mX_val[:, [38;5;241m0[39m])
[1;32m     13[0m mae [38;5;241m=[39m mean_absolute_error(y_val, y_val_pred)
[1;32m     14[0m rmse [38;5;241m=[39m mean_squared_error(y_val, y_val_pred) [38;5;241m*[39m[38;5;241m*[39m [38;5;241m0.5[39m

[0;31mNameError[0m: name 'polysin_result' is not defined
NameError: name 'polysin_result' is not defined

